### ISSUE TITLE
Create files below dev - custom rules definition not working

### ISSUE THREAD

**Issue by unktone** [falcosecurity/rules#104]
**Describe the bug**

I am attempting to override the "Create files below dev" rule by creating a rules file as such:

customRules:
  my-post-rules.yaml: |-
    - rule: Create files below dev
      enabled: false

This rule continues to trigger.  I have tried using append: true to no avail.  I have tried to add conditions to the macro for exceptions and could not get that to work either.

I was able to quit down the /etc alert to /etc/hosts, so I know that macro is working.  

This is the full file I am attempting to use:
my-post-rules.yaml: |-
    - rule: Java Process Class File Download
      enabled: false
    - rule: Write below etc
      enabled: false
    - rule: Create files below dev
      enabled: false
    - macro: user_known_write_below_etc_activities
      condition: fd.name="/etc"
    - rule: Detect Write Below /etc/hosts
      desc: an attempt to write to /etc/hosts file (CVE-2020-8557)
      condition: open_write and container and fd.name=/etc/hosts
      output: "File /etc/hosts opened for writing (user=%user.name command=%proc.cmdline parent=%proc.pname pcmdline=%proc.pcmdline file=%fd.name program=%proc.name gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)"
      priority: ERROR
      tags: [filesystem, mitre_persistence]

**How to reproduce it**

1. Deploy falco with helm
2. add a section to your vaules file:
customRules:
  my-post-rules.yaml: |-
    - rule: Create files below dev
      enabled: false
3. trigger the rule condition
4. observe the event continue to occur and alert

**Expected behaviour**

I believe with the setup here, that the Create files below dev rule should not trigger.

**Screenshots**

**Environment**

- Falco version:
{"default_driver_version":"4.0.0+driver","driver_api_version":"3.0.0","driver_schema_version":"2.0.0","engine_version":"16","falco_version":"0.34.1","libs_version":"0.10.4","plugin_api_version":"2.0.0"}

- System info:
"system_info":{"machine":"x86_64","nodename":"falco-9c8s6","release":"5.4.226-129.415.amzn2.x86_64","sysname":"Linux","version":"#1 SMP Fri Dec 9 12:54:21 UTC 2022"},"version":"0.34.1"}

- Cloud provider or hardware configuration:

```
- image:
  registry: docker.internal-my.com/docker-hub
falco:
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d/my-post-rules.yaml
  log_level: error
  priority: error
falcoctl:
  image:
    registry: docker.internal-my.com/docker-hub
driver:
  loader:
    initContainer:
      image:
        registry: docker.internal-my.com/docker-hub
falcosidekick:
  enabled: true
  config:
    aws:
      s3:
        bucket: falco-logs-{{ .Values.spec.environment }}
  image:
    registry: docker.internal-my.com/docker-hub
    repository: falcosecurity/falcosidekick
  webui:
    image:
      registry: docker.internal-my.com/docker-hub
    redis:
      image:
        registry: docker.internal-my.com/docker-hub
customRules:
  my-post-rules.yaml: |-
    - rule: Java Process Class File Download
      enabled: false
    - rule: Write below etc
      enabled: false
    - rule: Create files below dev
      enabled: false
    - macro: user_known_write_below_etc_activities
      condition: fd.name="/etc"
    - rule: Detect Write Below /etc/hosts
      desc: an attempt to write to /etc/hosts file (CVE-2020-8557)
      condition: open_write and container and fd.name=/etc/hosts
      output: "File /etc/hosts opened for writing (user=%user.name command=%proc.cmdline parent=%proc.pname pcmdline=%proc.pcmdline file=%fd.name program=%proc.name gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)"
      priority: ERROR
      tags: [filesystem, mitre_persistence]
```

- OS:
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel:
Linux falco-9c8s6 5.4.226-129.415.amzn2.x86_64 #1 SMP Fri Dec 9 12:54:21 UTC 2022 x86_64 GNU/Linux

- Installation method:
Kubernetes, Helm

**Additional context**
