### ISSUE TITLE
Falco Rules Doc Comments

### ISSUE THREAD

**Issue by leogr** [falcosecurity/rules#150]
**Motivation**

The issues I found with comments are due to practical reasons. In particular:

- There should be no empty lines between the comments and the referred item
  - This will avoid ambiguities. 
  - I guess I mostly fixed that with this PR.
- There's no standard item's comment structure
  - I would love to define a simple _Rule Doc_ convention (i.e., something similar to [Go Doc Comments](https://go.dev/doc/comment), but simpler)
- There's no clear way to distinguish sections from item's comment 

**Feature**

Implement a simple _Rules Doc Comments_ guideline and add it to the rules style guide.

**Alternatives**

Just rely on an existing convention, if any, or do nothing. However they don't look like compelling alternatives.

**Additional context**

See https://github.com/falcosecurity/rules/pull/149#issuecomment-1704317483

**Comment by leogr** [comment]
@incertum do you think this is still valuable? wdyt?

cc @LucaGuerra

**Comment by incertum** [comment]
still relevant

/remove-lifecycle stale

**Comment by leogr** [comment]
cc @falcosecurity/falco-website-maintainers

**Comment by leogr** [comment]
This is still a thing, IMO.

cc @falcosecurity/rules-maintainers
/help
/lifecycle stale

**Comment by leogr** [comment]
/remove-lifecycle rotten
/remove-lifecycle stale

@LucaGuerra @Issif May you help with this?

**Comment by leogr** [comment]
I've been thinking about this more and I believe the core of the convention can be kept very simple, borrowing from Go Doc Comments.

The key rule: a doc comment is a comment block with no blank line between it and the item it documents. Any comment separated by a blank line is a section comment or a standalone note, not an item's doc comment.

```yaml
  # This is a section comment (blank line above AND below separates it from items)

  # This is a doc comment for the macro below (no blank line between).
  # It can span multiple lines for tuning guidance, rationale, etc.
  - macro: container
    condition: (container.id != host)
```

This alone resolves the ambiguity problem. From there, we can layer on a few lightweight conventions:

  - First sentence of a doc comment should summarize the item's purpose
  - Tuning macros (user_*, allowed_*) should include a brief override example in their doc comment
  - Source attribution (URLs, commands used to derive a list) goes in the doc comment
  - Commented-out code should include a reason or be removed (git has history)

This is especially valuable for macros and lists, which lack a desc field and currently rely entirely on ad hoc comments for documentation.

Finally, the YAML linter should be fixed as well, and it should support this style.

I will likely work on this soon.
