### ISSUE TITLE
BPF Program Not Profiled Rule with systemd

### ISSUE THREAD

**Issue by rriverak** [falcosecurity/rules#287]
Hey,
currently we are facing False-Positive Events from the `BPF Program Not Profiled` Rule.
The Event was triggered by systemd, here is an example Log from Falco:
```json
{"hostname":"node-4711","output":"11:28:29.271623114: Notice BPF Program Not Profiled (bpf_cmd=5 evt_type=bpf user=root user_uid=0 user_loginuid=-1 process=systemd proc_exepath=/usr/lib/systemd/systemd parent=<NA> command=systemd terminal=0 exe_flags=<NA> container_id=host container_image=<NA> container_image_tag=<NA> container_name=host k8s_ns=<NA> k8s_pod_name=<NA>)","output_fields":{"container.id":"host","container.image.repository":null,"container.image.tag":null,"container.name":"host","evt.arg.cmd":"5","evt.arg.flags":null,"evt.time":1746617309271623114,"evt.type":"bpf","k8s.ns.name":null,"k8s.pod.name":null,"proc.cmdline":"systemd","proc.exepath":"/usr/lib/systemd/systemd","proc.name":"systemd","proc.pname":null,"proc.tty":0,"user.loginuid":-1,"user.name":"root","user.uid":0},"priority":"Notice","rule":"BPF Program Not Profiled","source":"syscall","tags":["TA0003","container","host","maturity_sandbox","mitre_persistence"],"time":"2025-05-07T11:28:29.271623114Z"}
```

as you can see, the `process`  and the `proc.name` is set to `systemd` in our Event.  

But if we look at the rule [`BPF Program Not Profiled`](https://github.com/falcosecurity/rules/blob/75a39c1dee9309b019ffd4576ad3fe73f9e9f0a2/rules/falco-incubating_rules.yaml#L1294C1-L1295C1), especially the part [`bpf_profiled_binaries`](https://github.com/falcosecurity/rules/blob/75a39c1dee9309b019ffd4576ad3fe73f9e9f0a2/rules/falco-incubating_rules.yaml#L1288C1-L1290C1), we can see that systemd is already in the trusted binaries list. 

We are now wondering why we still get this event for systemd and would be happy to get some advice here.

Falco: 0.40.0
Helm: 4.21.3
Kubernetes: 1.30.1
Ubuntu: 24.04

**Comment by katsew** [comment]
I'm having the same issue.
I'm not sure why this works fine, but I currently workaround by overriding the list with the same items.

```
    - list: bpf_profiled_binaries
      override:
        items: replace
      items:
        - falco
        - bpftool
        - systemd
```

**Comment by rriverak** [comment]
Hey @katsew,
thanks for this verry helpful hint!

I rechecked the logs of our Falco pods again and realized that we are actually using old rules! 
```json
{"level":"INFO","msg":"Resolving dependencies ...","timestamp":"2025-05-07 16:18:47"}
{"level":"INFO","msg":"Installing artifacts","refs":["ghcr.io/falcosecurity/rules/falco-rules:2","ghcr.io/falcosecurity/rules/falco-incubating-rules:2","ghcr.io/falcosecurity/rules/falco-sandbox-rules:2"],"timestamp":"2025-05-07 16:18:49"}
{"level":"INFO","msg":"Preparing to pull artifact","ref":"ghcr.io/falcosecurity/rules/falco-rules:2","timestamp":"2025-05-07 16:18:49"}
{"level":"INFO","msg":"Pulling layer 5edca1a8eea6","timestamp":"2025-05-07 16:18:50"}
{"level":"INFO","msg":"Pulling layer 48b6c5ae7a61","timestamp":"2025-05-07 16:18:50"}
{"level":"INFO","msg":"Pulling layer 8ac74658d3a4","timestamp":"2025-05-07 16:18:50"}
{"digest":"ghcr.io/falcosecurity/rules/falco-rules@sha256:8ac74658d3a4b3d4db6228db23b5706c1cf5e25f33c8eb33881e28f660a43828","level":"INFO","msg":"Verifying signature for artifact","timestamp":"2025-05-07 16:18:50"}
{"level":"INFO","msg":"Signature successfully verified!","timestamp":"2025-05-07 16:18:51"}
{"file":"falco_rules.yaml.tar.gz","level":"INFO","msg":"Extracting and installing artifact","timestamp":"2025-05-07 16:18:51","type":"rulesfile"}
```

If you can see in the Logs, we pull the Rules Image with tag `2` which is maybe outdated.
at Tag `2`, the rule was still in sandbox and had no systemd in the List. 
https://github.com/falcosecurity/rules/blob/97308654f2e43baca516f61d5b43c5cfc7eb6e10/rules/falco-sandbox_rules.yaml#L1695-L1696

systemd was added to the list with the start of ruleset tag `3` or version 3.2.0.
https://github.com/falcosecurity/rules/blob/b6ad37371923b28d4db399cf11bd4817f923c286/rules/falco-incubating_rules.yaml#L1288-L1289


If I now look at the official helmet chart, version 3 of the Rules is to default. 
https://github.com/falcosecurity/charts/blob/6db1b396ae76741588208a437f8f7d44a2bee91e/charts/falco/values.yaml#L552-L553

So we will now update our rules to “3” and expect this to solve the problem :)

**Comment by katsew** [comment]
Hi @rriverak,

Thanks for the feedback!
In my case, I tried to download falco rules with this falcoctl.yaml, expects the latest v3 rules([sha256:de2cd036fd7f9bb87de5d62b36d0f35ff4fa8afbeb9a41aa9624e5f6f9a004e1](https://github.com/falcosecurity/rules/pkgs/container/rules%2Ffalco-rules)), but It seems that this refs download old ones.

```
    artifact:
      allowedTypes:
      - rulesfile
      - plugin
      follow:
        every: 6h
        falcoversions: http://localhost:8765/versions
        pluginsDir: /plugins
        refs:
        - falco-rules:3
        - falco-incubating-rules:3
        - falco-sandbox-rules:3
        rulesfilesDir: /rulesfiles
      install:
        pluginsDir: /plugins
        refs:
        - falco-rules:3
        - falco-incubating-rules:3
        - falco-sandbox-rules:3
        resolveDeps: true
        rulesfilesDir: /rulesfiles
    indexes:
    - name: falcosecurity
      url: https://falcosecurity.github.io/falcoctl/index.yaml
```

Alternatively I try dropping version number from refs which download the latest rule files, then it download the correct rule files you've mentioned.

```
    artifact:
      allowedTypes:
      - rulesfile
      - plugin
      follow:
        every: 6h
        falcoversions: http://localhost:8765/versions
        pluginsDir: /plugins
        refs:
        - falco-rules
        - falco-incubating-rules
        - falco-sandbox-rules
        rulesfilesDir: /rulesfiles
      install:
        pluginsDir: /plugins
        refs:
        - falco-rules
        - falco-incubating-rules
        - falco-sandbox-rules
        resolveDeps: true
        rulesfilesDir: /rulesfiles
    indexes:
    - name: falcosecurity
      url: https://falcosecurity.github.io/falcoctl/index.yaml
```

So the root cause of this issue is rule file versioning does not work as expected? 🤔
