### ISSUE TITLE
recognize azurefile-csi

### ISSUE THREAD

**Issue by kellybirr** [falcosecurity/rules#69]
**Motivation**

`azuredisk-csi` is recognized in `known_aks_mount_in_privileged_containers` but `azurefile-csi` is not

**Feature**

Add this repository to the recognized list

**Alternatives**

n/a

**Additional context**

*updated macro*
```yaml
- macro: known_aks_mount_in_privileged_containers
  condition:
    (k8s.ns.name = kube-system and container.image.repository in (mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi,mcr.microsoft.com/oss/kubernetes-csi/azurefile-csi)
    or k8s.ns.name = system and container.image.repository = mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver)
```
